var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/red-envelopes/route.js")
R.c("server/chunks/_1_tcb7n._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/[root-of-the-server]__0yw1mha._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/[root-of-the-server]__1y_g68p._.js")
R.c("server/chunks/_1-7w55a._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_red-envelopes_route_actions_1ljduxt.js")
R.m(65886)
module.exports=R.m(65886).exports
