ALTER TABLE "Admin"
  ADD COLUMN "permissions" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "sessionVersion" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "createdById" TEXT,
  ADD COLUMN "lastLoginAt" TIMESTAMP(3);
ALTER TABLE "Admin" ADD CONSTRAINT "Admin_createdById_fkey"
  FOREIGN KEY ("createdById") REFERENCES "Admin"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
