var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0vcu5aa._.js")
R.c("server/chunks/ssr/node_modules_1c76tvq._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0cz7t1p.js")
R.c("server/chunks/ssr/node_modules_next_dist_17i19if._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xd5ha7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jlf4i0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_1oy1nwh.js")
R.c("server/chunks/ssr/src_app_1v9y2bh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_0pt47yr.js")
R.m(52993)
module.exports=R.m(52993).exports
