ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'LIVE_TARGET_REWARD';
CREATE TABLE "LiveCommerceRule" (
  "id" TEXT NOT NULL DEFAULT 'LIVE', "version" INTEGER NOT NULL DEFAULT 1,
  "hostShareBps" INTEGER NOT NULL DEFAULT 4000, "agencyShareBps" INTEGER NOT NULL DEFAULT 2000,
  "companyShareBps" INTEGER NOT NULL DEFAULT 4000, "rewardsEnabled" BOOLEAN NOT NULL DEFAULT false,
  "targetCoins" BIGINT NOT NULL DEFAULT 0, "rewardCoins" BIGINT NOT NULL DEFAULT 0,
  "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "LiveCommerceRule_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "VideoLiveSession"
  ADD COLUMN "liveRuleVersion" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "rewardTargetCoins" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN "targetRewardCoins" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN "eligibleGiftCoins" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN "targetRewardPaid" BOOLEAN NOT NULL DEFAULT false;
