var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/room-backgrounds/custom/[requestId]/preview/route.js")
R.c("server/chunks/[root-of-the-server]__10xfvbb._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_1_tcb7n._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/[root-of-the-server]__1y_g68p._.js")
R.c("server/chunks/_1-7w55a._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/1jng_app_api_room-backgrounds_custom_[requestId]_preview_route_actions_02lco4s.js")
R.m(51027)
module.exports=R.m(51027).exports
