var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/room-games/route.js")
R.c("server/chunks/src_lib_game-control_0mfa02c._.js")
R.c("server/chunks/[root-of-the-server]__1j5egx3._.js")
R.c("server/chunks/_1_tcb7n._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_1-7w55a._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/[root-of-the-server]__1y_g68p._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_room-games_route_actions_1rw9wnc.js")
R.m(69540)
module.exports=R.m(69540).exports
