CREATE TABLE "VipTier" (
 "id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "level" INTEGER NOT NULL UNIQUE CHECK ("level" > 0),
 "validDays" INTEGER NOT NULL CHECK ("validDays" BETWEEN 1 AND 3650), "active" BOOLEAN NOT NULL DEFAULT true,
 "privileges" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE TABLE "VipBenefitAsset" (
 "tierId" TEXT NOT NULL REFERENCES "VipTier"("id") ON DELETE CASCADE ON UPDATE CASCADE,
 "privilege" TEXT NOT NULL, "assetId" TEXT NOT NULL REFERENCES "UploadAsset"("id") ON DELETE CASCADE ON UPDATE CASCADE,
 PRIMARY KEY ("tierId", "privilege", "assetId")
);
CREATE TABLE "VipMembership" (
 "userId" TEXT PRIMARY KEY REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
 "tierId" TEXT NOT NULL REFERENCES "VipTier"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
 "startsAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "expiresAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3)
);
CREATE INDEX "VipMembership_expiresAt_idx" ON "VipMembership"("expiresAt");
