"use client";
import Link from "next/link";
import { useState } from "react";

const input = "w-full rounded-xl border border-[#d9e5e2] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#16877d]";
export default function NotificationManager() {
  const [form,setForm]=useState({title:"",body:"",userId:""}),[error,setError]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
  async function submit(e){e.preventDefault();setSaving(true);setError("");setMessage("");try{const r=await fetch("/api/admin/notifications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||"Unable to send notification.");setForm({title:"",body:"",userId:""});setMessage(form.userId?"User notification sent.":"Global notification sent.");}catch(e){setError(e.message)}finally{setSaving(false)}}
  return <div className="space-y-7"><div><h2 className="text-2xl font-bold">Send notifications</h2><p className="mt-1 text-sm text-[#71847f]">Publish a global announcement or target one user by public ID. Connected users receive it immediately.</p></div>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message&&<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}<form onSubmit={submit} className="grid gap-4 rounded-2xl border border-[#dfe9e7] bg-white p-5 md:grid-cols-2"><label className="text-sm font-semibold">Title<input required maxLength={120} className={input} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="text-sm font-semibold">Target user ID <span className="font-normal text-[#71847f]">(blank = everyone)</span><input className={input} placeholder="USR-123456" value={form.userId} onChange={e=>setForm({...form,userId:e.target.value})}/></label><label className="text-sm font-semibold md:col-span-2">Message<textarea required maxLength={2000} rows={4} className={input} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><div className="md:col-span-2"><button disabled={saving} className="rounded-xl bg-[#183f3b] px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{saving?"Sending…":"Send notification"}</button></div></form><section className="rounded-2xl border border-[#dfe9e7] bg-white p-5"><h3 className="font-bold">Notification records</h3><p className="mt-2 text-sm text-[#71847f]">Sent notifications are now grouped by recipient in Message History.</p><Link href="/messages?type=SYSTEM" className="mt-3 inline-block text-sm font-semibold text-[#087f74]">Open System Notifications →</Link></section></div>;
}
