var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/events/[id]/rollback/route.js")
R.c("server/chunks/[root-of-the-server]__0m-4rmt._.js")
R.c("server/chunks/[root-of-the-server]__1es659x._.js")
R.c("server/chunks/_0kcbqps._.js")
R.c("server/chunks/_1_tcb7n._.js")
R.c("server/chunks/[root-of-the-server]__136hf4v._.js")
R.c("server/chunks/[root-of-the-server]__1y_g68p._.js")
R.c("server/chunks/_0-fyrkd._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_16a8f28._.js")
R.c("server/chunks/_next-internal_server_app_api_events_[id]_rollback_route_actions_0ehv0zn.js")
R.m(8477)
module.exports=R.m(8477).exports
