var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/uploads/[assetId]/file/route.js")
R.c("server/chunks/[root-of-the-server]__0paoqxv._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_1_tcb7n._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/[root-of-the-server]__1y_g68p._.js")
R.c("server/chunks/_1-7w55a._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_next-internal_server_app_api_uploads_[assetId]_file_route_actions_0tl-hof.js")
R.m(87733)
module.exports=R.m(87733).exports
