var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/games/admin/route.js")
R.c("server/chunks/src_lib_game-control_0mfa02c._.js")
R.c("server/chunks/[root-of-the-server]__1njhd4-._.js")
R.c("server/chunks/_1_tcb7n._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_1-7w55a._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/[root-of-the-server]__1y_g68p._.js")
R.c("server/chunks/_next-internal_server_app_api_games_admin_route_actions_044f4po.js")
R.m(43497)
module.exports=R.m(43497).exports
